require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/rubocop'

Layout/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Layout/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Layout/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Layout/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/Documentation:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'lib/wkhtmltopdf_runner/utils.rb'

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'spec/**/*_spec.rb'
